// Code generated by go test github.com/nholstein/yubihsm -generate-default-key; DO NOT EDIT.

package yubihsm

// defaultAuthKey is the pre-derived default YubiHSM2 authentication key.
const defaultAuthKey = "\t\vG\xdb\xedYVT\x90\x1d\xee\x1c\xc6U\xe4 Y/ԃ\xf7Y\xe2\x99\t\xa0LE\x05\xd2\xce\n"

func defaultEncryptionKey() (key SessionKey) {
	copy(key[:], defaultAuthKey[:len(key)])
	return
}

func defaultMACKey() (key SessionKey) {
	copy(key[:], defaultAuthKey[len(key):])
	return
}
